[package]
name = "guest"
version.workspace = true
edition.workspace = true

[dependencies]
wit-bindgen-rt = { version = "0.39.0", features = ["bitflags"] }

[package.metadata.component]
package = "component:example"